#!/usr/bin/perl
use strict;

my $usage=q/
 Usage
  wwput [<scp_opts>] <remote_dir> <local_files>...

  Note: scp -pr options are already provided.
/;

die "$usage\n" unless @ARGV>=2;
my $host='igm3.pha.jhu.edu';
my $opts;
while ($ARGV[0]=~m/^\-[BCpqrv\d]+/) {
 $opts.=shift(@ARGV).' ';
 }

my $rpath=shift(@ARGV);
$rpath=$ENV{PWD} if $rpath eq '.';
$rpath=~s{^/.+?/httpd/ccb}{/data1/igm3/www/ccb.jhu.edu};
my $cmd='scp '.$opts.' -pr '." '".join("' '",@ARGV)."' $host\:".$rpath;
system($cmd);

